version: "3.8"
services:
    mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
    seq:
      image: datalust/seq:latest
      ports:
        - "5341:80"
      environment:
        - ACCEPT_EULA=Y
      volumes:
        - seq_data:/data
volumes:
  mongodb_data:
  seq_data: